config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'collections/:id' => 'pages#show_collection', :via => :get
    match 'get_authtoken' => 'users#get_resourcemap_token', :via => :post

    resources :settings

end

app/models/setting.rb
class Setting < ActiveRecord::Base    
  validates_presence_of :url

  attr_accessible :url
  attr_accessible :email
  attr_accessible :password
  attr_accessible :token

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController  
  before_filter :authenticate_user!

  def index
    @setting = Setting.first
  end

  def update
  	@setting = Setting.find(params[:id])
  	if(@setting.update_attributes(params[:setting]))
  		redirect_to settings_path
  	else
  		render :edit
  	end    
  end

  def show
  	
  end

end

app/views/settings/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@setting, :url => setting_path(@setting) ,:method => 'put', :html => {:class => 'form-horizontal'} ) do |f| %> 
          <fieldset>
            <legend class="text-left">Resourcemap Configuration</legend>
    
            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-4 control-label">Resourcemap URL</label>
              <div class="col-md-8">
                <%= f.text_field :url, :class =>"form-control", :required => "required", :placeholder => "Resourcemap url homepage" %>
              </div>
            </div>

            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-4 control-label">Email</label>
              <div class="col-md-8">
                <%= f.text_field :email, :class =>"form-control", :required => "required", :placeholder => "Email login to resourcemap as super admin" %>
              </div>
            </div>
    
            <!-- Password input-->
            <div class="form-group">
              <label class="col-md-4 control-label">Password</label>
              <div class="col-md-8">
                <%= f.text_field :password, :class =>"form-control", :required => "required", :placeholder => "Secret password" %>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <label class="col-md-4 control-label"></label>
              <div class="col-md-4 text-left">
                <a class="btn btn-info" id="btn-test-connection" onclick="connectToResourcemap()">Test Connection</a>
              </div>
            </div>

            <!-- Token input-->
            <div class="form-group">
              <label class="col-md-4 control-label">Authentication Token</label>
              <div class="col-md-8">
                <%= f.text_field :token, :class =>"form-control", :required => "required", :placeholder => "Token to connect to resourcemap", :readonly => "readonly" %>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <label class="col-md-4 control-label"></label>
              <div class="col-md-4 text-left">
                <button class="btn btn-primary">Update</button>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
</div>