config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'collections/:id' => 'pages#show_collection', :via => :get
    match 'get_authtoken' => 'users#get_resourcemap_token', :via => :post

    resources :settings

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resourcemap Monitoring</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "datepicker", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "bootstrap-datepicker", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar">
      <div class="navbar-inner sabay-header">
        <div class="hearder_narrow">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
          <a class="brand" href="/" name="top">
            <img src="/images/logo.png" alt="..." class="img-rounded">
          </a>
          <% if current_user %>
            <div class="pull-right right-menu" style="padding-right:10px;">
            	Welcome <b><%= current_user.email %></b> | 
            	<a type="button" href="<%= settings_path(@user) %>" style="padding-right:10px;color:grey;">
				        <span><i class="glyphicon glyphicon-cog"></i></span>
				        SETTING
				      </a>
              <%= link_to "Sign Out ", destroy_user_session_path(), :method => :delete, :class => "btn btn-danger" %>
            </div>
          <% end %>
        <!--/.nav-collapse -->
        </div>
      <!--/.container-fluid -->
      </div>
    <!--/.navbar-inner -->
    </div>
    <%= yield %>
    <div style="clear:both;"></div>
	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resourcemap Monitoring</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar" style="border: 0px">
      <div class="navbar-inner sabay-header">
        <div class="hearder_narrow">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
          <a class="brand" href="/" name="top">
            <img src="/images/logo.png" alt="..." class="img-rounded">
          </a>
        <!--/.nav-collapse -->
        </div>
      <!--/.container-fluid -->
      </div>
    <!--/.navbar-inner -->
    </div>
    <%= yield %>
  </body>
</html>